// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTY1wqEM2fW2CnxyXAe2FDH9s4b9MOLg',
    appId: '1:705689292446:web:55ebe89e8fa562d6a9f58f',
    messagingSenderId: '705689292446',
    projectId: 'inventory-10900',
    authDomain: 'inventory-10900.firebaseapp.com',
    storageBucket: 'inventory-10900.firebasestorage.app',
    measurementId: 'G-C83W0FTEK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGXTfuBP4x4rW3qXVH8dLPH9sfOkagS8',
    appId: '1:705689292446:android:289b9e3350f53567a9f58f',
    messagingSenderId: '705689292446',
    projectId: 'inventory-10900',
    storageBucket: 'inventory-10900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGUGpN85fecRAs7AwgRBN5UbopQySVQd0',
    appId: '1:705689292446:ios:9ac395b71996c309a9f58f',
    messagingSenderId: '705689292446',
    projectId: 'inventory-10900',
    storageBucket: 'inventory-10900.firebasestorage.app',
    iosBundleId: 'com.example.codeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGUGpN85fecRAs7AwgRBN5UbopQySVQd0',
    appId: '1:705689292446:ios:9ac395b71996c309a9f58f',
    messagingSenderId: '705689292446',
    projectId: 'inventory-10900',
    storageBucket: 'inventory-10900.firebasestorage.app',
    iosBundleId: 'com.example.codeScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChTY1wqEM2fW2CnxyXAe2FDH9s4b9MOLg',
    appId: '1:705689292446:web:bf892ec1083934bda9f58f',
    messagingSenderId: '705689292446',
    projectId: 'inventory-10900',
    authDomain: 'inventory-10900.firebaseapp.com',
    storageBucket: 'inventory-10900.firebasestorage.app',
    measurementId: 'G-XTDNPNSWEL',
  );
}
